CONFIG_NAME: base  #base, full_frozen, shared, test
dataset_name: lfw #facescrub, cifar100
class_range: 2870 #(276, 25), 
total_step: 1 #10

# machine setup 
num_workers: 4 
gpu_id: [0]
manual_seed: 100

# model arch
img_size: 112
model_type: arcface
num_classes: 2870 #(276, 250)
final_dim: 512 
metric: arc_margin 
easy_margin: False
loss: focal_loss 
optimizer: sgd 
use_se: False


lr_shared_layer: 0.0001 #1e-4
temperature: 2



# training settings 
lr_image_train: 0.1   #0.1 for ArcFace
gamma: 0.1  #0.5
weight_decay: 0.0005 #0.0005 for base, 0.0001 for IL
momentum: 0.9
KD: 8
kl_div: 400
att_distill: 2 

max_epoch: 15
batch_size: 128  
valid_interval: 1
save_interval: 2

# test settings
is_unseen: True
num_imposter_per_sub: 10 
seen_steps: 4

#save
roc_file: arc_concat
is_roc: False

# flags
do_valid: True  
is_ident: False  


# directory & path
data_dir: ./data
checkpoints_path: ./checkpoints

# no pretrained weigths for CL experiments
is_pretrain: False
arcface_pretrain_path: ./weights/pretrain/arcface_ir18_ms1mv3.pth
adaface_pretrain_path: ./weights/pretrain/adaface_ir18_webface4m.ckpt

# base = True for base training
is_base: False 
arcface_base_path: ./weights/facescrub/base/arcface_ir18.pth
adaface_base_path: ./weights/facescrub/base/adaface_ir18.pth

arcface_test_path: ./checkpoints/facescrub/shared/arcface/arcface_ir18.pth