CONFIG_NAME: JT #base, shared, test
dataset_name: lfw 
class_range: 2870 #287
total_step: 1 #10

# machine setup 
num_workers: 4 
gpu_id: [0]
manual_seed: 100

# model arch
img_size: 112
model_type: arcface
num_classes: 2870 #287
final_dim: 512 
metric: arc_margin 
easy_margin: False
loss: focal_loss 
optimizer: sgd 
use_se: False
s: 11
m: 0.0


lr_base_training: [8, 10, 11]
lr_shared_training: [2, 8, 11]
lr_shared_layer: 0.0001 #1e-4
temperature: 2

# objective function 
lr_image_train: 0.1   #0.1 for ArcFace
gamma: 0.1  #0.5
weight_decay: 0.0001 #0.0005 for base, 0.0001 for IL
momentum: 0.9
KD: 8
kl_div: 550
att_distill: 2 

# training settings 
max_epoch: 12  #15
batch_size: 128  
valid_interval: 1
save_interval: 1

# test settings
is_unseen: False 
num_imposter_per_sub: 1 
seen_steps: 10

#save
roc_file: arc_concat
is_roc: False

# flags
do_valid: True  
is_ident: False  


# directory & path
data_dir: ./data
checkpoints_path: ./checkpoints

# no pretrained weigths for CL experiments
is_pretrain: False
arcface_pretrain_path: ./weights/pretrain/arcface_ir18_ms1mv3.pth
adaface_pretrain_path: ./weights/pretrain/adaface_ir18_webface4m.ckpt

# base = True for base training
is_base: False  
arcface_base_path: ./weights/lfw/base/arcface_ir18.pth
adaface_base_path: ./weights/lfw/base/adaface_ir18.pth

arcface_test_path: ./checkpoints/lfw/shared/arcface/arcface_ir18.pth
arcface_full_model_path: ./checkpoints/lfw/JT/arcface/best.pth 